manifestVersion = 0

[package]
  type = "mod"
  name = "spawner-config"
  description = "A server-side mod that allows for behavior tweaks to Mob Spawners."
  version = "1.0.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = ">=1.16.2"
  fabric = "*"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
